import { useEffect, useMemo, useState } from 'react';
import { datasetsApi, evaluationsApi, recipesApi, type EvaluationRun, type EvaluationRunSummary, type EvaluationStatus, type RecipeSummary, type TestDatasetSummary } from '../api';
import { Badge, Button, EmptyState, InlineError, Kpi, Modal, Panel, ProgressBar, SearchInput } from '../components/ui';
import { errorMessage, number, pct, shortDate } from '../lib/format';

function EvaluationWizard({datasets,recipes,onClose,onCreated}:{datasets:TestDatasetSummary[];recipes:RecipeSummary[];onClose:()=>void;onCreated:(id:string)=>void}) {
  const [datasetId,setDatasetId]=useState(datasets[0]?.dataset_id??'');const [recipeName,setRecipeName]=useState(recipes[0]?.name??'');const [imageInput,setImageInput]=useState('image');const [decisionOutput,setDecisionOutput]=useState('result');const [scoreOutput,setScoreOutput]=useState('score');const [capture,setCapture]=useState(true);const [failUnlabeled,setFailUnlabeled]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const submit=async()=>{if(!datasetId||!recipeName)return;setBusy(true);setError(null);try{const r=await evaluationsApi.create({dataset_id:datasetId,recipe_name:recipeName,image_input_name:imageInput,decision_output:decisionOutput,score_output:scoreOutput||null,ok_label:'OK',ng_label:'NG',shared_image_inputs:{},constant_inputs:{},capture_node_values:capture,fail_on_unlabeled:failUnlabeled});onCreated(r.evaluation_id);onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
  return <Modal title="New Evaluation" onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button variant="primary" onClick={submit} disabled={busy||!datasetId||!recipeName}>{busy?'Submitting...':'Run Evaluation'}</Button></>}><InlineError message={error}/><div className="form-grid"><div className="form-group"><label>Test Dataset</label><select className="select" value={datasetId} onChange={e=>setDatasetId(e.target.value)}>{datasets.map(d=><option key={d.dataset_id} value={d.dataset_id}>{d.name} ({d.image_count})</option>)}</select></div><div className="form-group"><label>Decision Recipe</label><select className="select" value={recipeName} onChange={e=>setRecipeName(e.target.value)}>{recipes.map(r=><option key={r.name} value={r.name}>{r.display_name} ({r.kind})</option>)}</select></div><div className="form-group"><label>Image Input</label><input className="input" value={imageInput} onChange={e=>setImageInput(e.target.value)}/></div><div className="form-group"><label>Decision Output</label><input className="input" value={decisionOutput} onChange={e=>setDecisionOutput(e.target.value)}/></div><div className="form-group"><label>Score Output</label><input className="input" value={scoreOutput} onChange={e=>setScoreOutput(e.target.value)}/></div></div><div className="divider"/><div className="checkbox-row"><label><input type="checkbox" checked={capture} onChange={e=>setCapture(e.target.checked)}/> Capture Node Values</label><label><input type="checkbox" checked={failUnlabeled} onChange={e=>setFailUnlabeled(e.target.checked)}/> Fail On Unlabeled</label></div><div className="annotation-note" style={{marginTop:12}}>Submit 시 Dataset/Recipe revision이 snapshot으로 저장되고 Job Queue에 등록됩니다.</div></Modal>;
}

function ResultsModal({run,onClose}:{run:EvaluationRun;onClose:()=>void}) {
  const [items,setItems]=useState(run.results??[]);const [error,setError]=useState<string|null>(null);const [filter,setFilter]=useState('all');
  useEffect(()=>{const q=filter==='wrong'?'?correct=false':filter==='error'?'?errors_only=true':'';void evaluationsApi.results(run.evaluation_id,q).then(r=>setItems(r.items)).catch(e=>setError(errorMessage(e)));},[filter,run.evaluation_id]);
  return <Modal title={`Evaluation Results · ${run.evaluation_id}`} onClose={onClose} footer={<Button onClick={onClose}>Close</Button>}><InlineError message={error}/><div style={{display:'flex',gap:6,marginBottom:10}}><Button onClick={()=>setFilter('all')}>All</Button><Button onClick={()=>setFilter('wrong')}>Incorrect</Button><Button onClick={()=>setFilter('error')}>Errors</Button></div><div className="table-wrap"><table><thead><tr><th>Image</th><th>GT</th><th>Prediction</th><th>Score</th><th>Correct</th><th>Latency</th></tr></thead><tbody>{items.map(x=><tr key={x.image_id}><td title={x.file_path}>{x.image_id}</td><td>{x.ground_truth}</td><td><Badge status={x.prediction==='ERROR'?'failed':x.prediction==='NG'?'queued':'completed'}>{x.prediction}</Badge></td><td>{x.score==null?'-':number(x.score,4)}</td><td>{x.correct==null?'-':x.correct?'✓':'✕'}</td><td>{number(x.duration_ms,1)} ms</td></tr>)}</tbody></table></div></Modal>;
}

const ACTIVE:EvaluationStatus[]=['queued','running','cancel_requested'];

export function EvaluationPage() {
  const [runs,setRuns]=useState<EvaluationRunSummary[]>([]);const [datasets,setDatasets]=useState<TestDatasetSummary[]>([]);const [recipes,setRecipes]=useState<RecipeSummary[]>([]);const [selectedId,setSelectedId]=useState('');const [detail,setDetail]=useState<EvaluationRun|null>(null);const [wizard,setWizard]=useState(false);const [resultsOpen,setResultsOpen]=useState(false);const [search,setSearch]=useState('');const [statusFilter,setStatusFilter]=useState('');const [error,setError]=useState<string|null>(null);
  const load=async()=>{try{const [r,d,rc]=await Promise.all([evaluationsApi.list(statusFilter?{status:statusFilter as EvaluationStatus}:{}),datasetsApi.list(),recipesApi.list()]);setRuns(r);setDatasets(d);setRecipes(rc);if(!selectedId&&r.length)setSelectedId(r[0].evaluation_id);}catch(e){setError(errorMessage(e));}};
  useEffect(()=>{void load();const t=window.setInterval(()=>void load(),2000);return()=>window.clearInterval(t);},[statusFilter]);
  useEffect(()=>{if(!selectedId){setDetail(null);return;}void evaluationsApi.get(selectedId).then(setDetail).catch(e=>setError(errorMessage(e)));},[selectedId,runs]);
  const filtered=useMemo(()=>runs.filter(r=>`${r.evaluation_id} ${r.dataset.name} ${r.recipe.name}`.toLowerCase().includes(search.toLowerCase())),[runs,search]);const active=runs.filter(r=>ACTIVE.includes(r.status));const summary=detail?.summary;
  const cancel=async(id:string)=>{try{await evaluationsApi.cancel(id);await load();}catch(e){setError(errorMessage(e));}};const remove=async()=>{if(!detail||ACTIVE.includes(detail.status)||!window.confirm('Evaluation을 삭제할까요?'))return;try{await evaluationsApi.remove(detail.evaluation_id);setSelectedId('');setDetail(null);await load();}catch(e){setError(errorMessage(e));}};
  return <div className="page">{wizard&&<EvaluationWizard datasets={datasets} recipes={recipes} onClose={()=>setWizard(false)} onCreated={(id)=>{setSelectedId(id);void load();}}/>}{resultsOpen&&detail&&<ResultsModal run={detail} onClose={()=>setResultsOpen(false)}/>}<div className="page-toolbar"><div className="page-title">평가</div><span className="page-subtitle">Job Queue 기반 Dataset + Decision Recipe 성능 검증</span><div style={{width:210}}><SearchInput placeholder="Evaluation 검색" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button variant="primary" onClick={()=>setWizard(true)}>New Evaluation</Button></div>{error&&<div className="status-strip"><InlineError message={error}/></div>}<div className="page-content" style={{overflow:'hidden'}}><div className="eval-layout">
    <div className="active-jobs">{active.length?active.slice(0,3).map(r=><div className="job-card" key={r.evaluation_id}><div className="job-top"><div className="job-title">{r.dataset.name}</div><Badge status={r.status}>{r.status}</Badge></div><div className="job-meta">{r.recipe.name} · {r.evaluation_id}</div><div className="job-progress"><ProgressBar value={r.progress.percent}/><strong>{r.progress.percent.toFixed(1)}%</strong></div><div className="job-meta">{r.progress.processed} / {r.progress.total} images {ACTIVE.includes(r.status)&&<button className="link-btn" onClick={()=>void cancel(r.evaluation_id)}>Cancel</button>}</div></div>):<div className="job-card"><div className="job-top"><div className="job-title">Evaluation Worker</div><Badge status="completed">Idle</Badge></div><div className="job-meta">No active jobs</div><div style={{height:24}}/><div className="job-meta">Interactive Recipe Run remains available</div></div>}</div>
    <div className="eval-main"><Panel title="Evaluation History" actions={<select className="select" style={{width:130}} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All Status</option><option>queued</option><option>running</option><option>completed</option><option>failed</option><option>cancelled</option></select>} flush><div className="table-wrap"><table><thead><tr><th>Evaluation ID</th><th>Status</th><th>Dataset</th><th>Recipe</th><th>Progress</th><th>Accuracy</th><th>F1</th><th>Created</th></tr></thead><tbody>{filtered.map(r=><tr key={r.evaluation_id} className={selectedId===r.evaluation_id?'selected':''} onClick={()=>setSelectedId(r.evaluation_id)}><td>{r.evaluation_id.slice(0,12)}</td><td><Badge status={r.status}>{r.status}</Badge></td><td>{r.dataset.name}</td><td>{r.recipe.name}</td><td>{r.progress.percent.toFixed(1)}%</td><td>{pct(r.summary?.metrics.accuracy)}</td><td>{pct(r.summary?.metrics.f1)}</td><td>{shortDate(r.created_at)}</td></tr>)}</tbody></table>{!filtered.length&&<EmptyState>No evaluations</EmptyState>}</div></Panel>
    <Panel title="Evaluation Detail" subtitle={detail?.evaluation_id??''} actions={detail&&!ACTIVE.includes(detail.status)?<Button variant="danger" onClick={remove}>Delete</Button>:undefined} flush>{detail?<div style={{padding:10}}><div className="detail-status-row"><Badge status={detail.status}>{detail.status}</Badge><ProgressBar value={detail.progress.percent}/><span>{detail.progress.processed}/{detail.progress.total}</span></div>{detail.failure&&<InlineError message={`${detail.failure.code}: ${detail.failure.message}`}/>} {summary?<><div className="kpi-grid" style={{gridTemplateColumns:'repeat(3,1fr)'}}><Kpi label="Accuracy" value={pct(summary.metrics.accuracy)}/><Kpi label="Recall" value={pct(summary.metrics.recall)}/><Kpi label="F1" value={pct(summary.metrics.f1)}/></div><div className="divider"/><div className="inspector-heading">Confusion Matrix</div><div className="matrix"><div className="axis"></div><div className="axis">Pred OK</div><div className="axis">Pred NG</div><div className="axis">GT OK</div><div className="good">TN<br/><strong>{summary.confusion_matrix.tn}</strong></div><div className="bad">FP<br/><strong>{summary.confusion_matrix.fp}</strong></div><div className="axis">GT NG</div><div className="bad">FN<br/><strong>{summary.confusion_matrix.fn}</strong></div><div className="good">TP<br/><strong>{summary.confusion_matrix.tp}</strong></div></div><div className="divider"/><div className="feature-list"><div><span>Evaluated Images</span><strong>{summary.evaluated_images}</strong></div><div><span>Errors</span><strong>{summary.error_images}</strong></div><div><span>Mean Latency</span><strong>{number(summary.latency.mean_ms,1)} ms</strong></div><div><span>P95 Latency</span><strong>{number(summary.latency.p95_ms,1)} ms</strong></div></div><div style={{marginTop:10}}><Button onClick={()=>setResultsOpen(true)}>View Results</Button></div></>:<EmptyState>{ACTIVE.includes(detail.status)?'Evaluation 진행 중입니다.':'Summary가 없습니다.'}</EmptyState>}</div>:<EmptyState>Evaluation을 선택하세요.</EmptyState>}</Panel></div>
  </div></div></div>;
}
