import { useEffect, useState } from 'react';
import { modelsApi, systemApi, type ModelSpec } from '../api';
import { Badge, Button, EmptyState, InlineError, Panel } from '../components/ui';
import { errorMessage } from '../lib/format';

const SETTINGS_KEY='image-processing-studio.settings';

type LocalSettings={theme:'dark';canvasGrid:boolean;autoFit:boolean;responseFormat:'json'|'zip';evaluationPolling:number};
const defaults:LocalSettings={theme:'dark',canvasGrid:true,autoFit:true,responseFormat:'json',evaluationPolling:2};

export function SettingsPage() {
  const [section,setSection]=useState('General');const [settings,setSettings]=useState<LocalSettings>(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)??'{}')}}catch{return defaults;}});const [connected,setConnected]=useState(false);const [models,setModels]=useState<ModelSpec[]>([]);const [error,setError]=useState<string|null>(null);const [saved,setSaved]=useState(false);
  const reload=async()=>{try{setError(null);const [h,m]=await Promise.all([systemApi.health(),modelsApi.list()]);setConnected(h.status==='ok');setModels(m);}catch(e){setConnected(false);setError(errorMessage(e));}};
  useEffect(()=>{void reload();},[]);
  const save=()=>{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));setSaved(true);window.setTimeout(()=>setSaved(false),1500);};
  return <div className="page"><div className="page-toolbar"><div className="page-title">설정</div><span className="page-subtitle">Frontend 환경 · Runtime · Model Registry · Developer</span><Button onClick={()=>void reload()}>Refresh Runtime</Button></div>{error&&<div className="status-strip"><InlineError message={error}/></div>}<div className="page-content" style={{overflow:'hidden'}}><div className="settings-layout"><Panel className="settings-nav" flush>{['General','Runtime','Model Registry','Developer'].map(x=><button className={`settings-item list-button ${section===x?'active':''}`} key={x} onClick={()=>setSection(x)}>{x}</button>)}</Panel><Panel><div className="settings-section">
    {section==='General'&&<><div className="settings-title">General</div><div className="settings-desc">브라우저에 저장되는 UI 기본 설정입니다.</div><div className="setting-row"><div><div className="setting-name">Theme</div><div className="setting-help">Application theme</div></div><select className="select" value={settings.theme} disabled><option>dark</option></select></div><div className="setting-row"><div><div className="setting-name">Canvas Grid</div><div className="setting-help">Recipe Canvas grid 표시</div></div><select className="select" value={settings.canvasGrid?'on':'off'} onChange={e=>setSettings(v=>({...v,canvasGrid:e.target.value==='on'}))}><option value="on">On</option><option value="off">Off</option></select></div><div className="setting-row"><div><div className="setting-name">Auto Fit</div><div className="setting-help">Recipe를 열 때 전체 Graph 자동 맞춤</div></div><select className="select" value={settings.autoFit?'on':'off'} onChange={e=>setSettings(v=>({...v,autoFit:e.target.value==='on'}))}><option value="on">On</option><option value="off">Off</option></select></div><div className="setting-row"><div><div className="setting-name">Default Response Format</div><div className="setting-help">Recipe 실행 기본 결과 형식</div></div><select className="select" value={settings.responseFormat} onChange={e=>setSettings(v=>({...v,responseFormat:e.target.value as 'json'|'zip'}))}><option value="json">JSON</option><option value="zip">ZIP</option></select></div><div className="setting-row"><div><div className="setting-name">Evaluation Polling</div><div className="setting-help">Job 상태 조회 주기</div></div><select className="select" value={settings.evaluationPolling} onChange={e=>setSettings(v=>({...v,evaluationPolling:Number(e.target.value)}))}><option value={1}>1 second</option><option value={2}>2 seconds</option><option value={5}>5 seconds</option></select></div><div style={{marginTop:14}}><Button variant="primary" onClick={save}>Save Settings</Button>{saved&&<span className="status-ok" style={{marginLeft:10}}>Saved</span>}</div></>}
    {section==='Runtime'&&<><div className="settings-title">Runtime</div><div className="settings-desc">실제 Backend API 연결 상태입니다.</div><div className="setting-row"><div><div className="setting-name">Backend</div><div className="setting-help">Vite proxy /api → localhost:8000</div></div><Badge status={connected?'completed':'failed'}>{connected?'Connected':'Disconnected'}</Badge></div><div className="setting-row"><div><div className="setting-name">Evaluation</div><div className="setting-help">Job Queue + single worker</div></div><span className="mono-small">202 Accepted / polling</span></div><div className="setting-row"><div><div className="setting-name">Synthetic NG</div><div className="setting-help">/api/v1/synthetic/*</div></div><span className="mono-small">Enabled</span></div></>}
    {section==='Model Registry'&&<><div className="settings-title">Model Registry</div><div className="settings-desc">Backend에 등록된 OpenCV ML 모델을 읽기 전용으로 조회합니다.</div>{models.length?<table><thead><tr><th>Model ID</th><th>Version</th><th>Algorithm</th><th>Labels</th><th>Feature Schema</th></tr></thead><tbody>{models.map(m=><tr key={`${m.model_id}-${m.version}`}><td>{m.model_id}</td><td>{m.version}</td><td>{m.algorithm}</td><td>{Object.values(m.labels).join(', ')||'-'}</td><td>{m.feature_schema}</td></tr>)}</tbody></table>:<EmptyState>No registered models</EmptyState>}</>}
    {section==='Developer'&&<><div className="settings-title">Developer</div><div className="settings-desc">FastAPI에서 제공하는 개발 문서로 이동합니다.</div><div style={{display:'flex',gap:6}}><Button onClick={()=>window.open('/docs','_blank')}>Swagger UI</Button><Button onClick={()=>window.open('/redoc','_blank')}>ReDoc</Button><Button onClick={()=>window.open('/openapi.json','_blank')}>OpenAPI JSON</Button></div></>}
  </div></Panel></div></div></div>;
}
