import { useEffect, useMemo, useRef, useState } from 'react';
import { syntheticApi, type DiffusionModelStatus, type SyntheticAssetSummary, type SyntheticCandidate, type SyntheticGenerateRequest, type SyntheticMethodInfo } from '../api';
import { Badge, Button, EmptyState, Field, InlineError, Kpi, Modal, Panel, SearchInput, Tabs } from '../components/ui';
import { errorMessage, imageDataUrl, number, parseJsonObject } from '../lib/format';

const maskTypes = ['random_blob','rectangle','ellipse','perlin','crack','manual','polygon'];
const proceduralPatterns = ['blob','stain','droplet','pooling','crack','speck','texture'];

function AssetModal({ onClose, onCreated }: { onClose:()=>void; onCreated:(asset:SyntheticAssetSummary)=>void }) {
  const [name,setName]=useState(''); const [category,setCategory]=useState(''); const [description,setDescription]=useState(''); const [tags,setTags]=useState('');
  const [image,setImage]=useState<File|null>(null); const [mask,setMask]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const create = async()=>{ if(!name||!category||!image) return setError('Name, Category, Image는 필수입니다.'); setBusy(true); setError(null); try { const asset=await syntheticApi.createAsset({name,category,description:description||null,tags:tags.split(',').map(x=>x.trim()).filter(Boolean),metadata:{}}, image, mask); onCreated(asset); onClose(); } catch(e){setError(errorMessage(e));} finally{setBusy(false);} };
  return <Modal title="Add Synthetic Asset" onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button variant="primary" onClick={create} disabled={busy}>{busy?'Saving...':'Save Asset'}</Button></>}>
    <InlineError message={error}/><div className="form-grid"><div className="form-group"><label>Name</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="form-group"><label>Category</label><input className="input" value={category} onChange={e=>setCategory(e.target.value)} placeholder="broken_wafer, droplet..."/></div><div className="form-group"><label>Asset Image</label><input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]??null)}/></div><div className="form-group"><label>Mask (optional)</label><input type="file" accept="image/*" onChange={e=>setMask(e.target.files?.[0]??null)}/></div><div className="form-group"><label>Tags</label><input className="input" value={tags} onChange={e=>setTags(e.target.value)} placeholder="wet, fragment"/></div><div className="form-group"><label>Description</label><input className="input" value={description} onChange={e=>setDescription(e.target.value)}/></div></div>
  </Modal>;
}

export function SyntheticNgPage() {
  const [methods,setMethods]=useState<SyntheticMethodInfo[]>([]); const [assets,setAssets]=useState<SyntheticAssetSummary[]>([]); const [models,setModels]=useState<DiffusionModelStatus[]>([]);
  const [method,setMethod]=useState('procedural'); const [defectType,setDefectType]=useState('anomaly'); const [severity,setSeverity]=useState(0.5); const [count,setCount]=useState(1); const [seed,setSeed]=useState('');
  const [maskType,setMaskType]=useState('random_blob'); const [centerX,setCenterX]=useState(0.5); const [centerY,setCenterY]=useState(0.5); const [widthRatio,setWidthRatio]=useState(0.18); const [heightRatio,setHeightRatio]=useState(0.18); const [feather,setFeather]=useState(3); const [polygonText,setPolygonText]=useState('[[0.40,0.40],[0.60,0.40],[0.55,0.60],[0.42,0.58]]');
  const [assetId,setAssetId]=useState(''); const [paramsText,setParamsText]=useState(JSON.stringify({pattern:'stain',opacity:0.5},null,2));
  const [source,setSource]=useState<File|null>(null); const [targetMask,setTargetMask]=useState<File|null>(null); const [assetImage,setAssetImage]=useState<File|null>(null); const [assetMask,setAssetMask]=useState<File|null>(null);
  const [sourceUrl,setSourceUrl]=useState<string|null>(null); const [candidates,setCandidates]=useState<SyntheticCandidate[]>([]); const [selectedIndex,setSelectedIndex]=useState(0); const [resultTab,setResultTab]=useState('Generated');
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [assetModal,setAssetModal]=useState(false); const [assetSearch,setAssetSearch]=useState('');
  const sourceRef=useRef<HTMLInputElement | null>(null);

  const reload = async()=>{ setError(null); try { const [m,a,d]=await Promise.all([syntheticApi.methods(),syntheticApi.assets(),syntheticApi.diffusionModels()]); setMethods(m); setAssets(a); setModels(d); if(!method&&m.length)setMethod(m[0].method); } catch(e){setError(errorMessage(e));} };
  useEffect(()=>{void reload();},[]);
  useEffect(()=>{ if(!source){setSourceUrl(null);return;} const url=URL.createObjectURL(source);setSourceUrl(url);return()=>URL.revokeObjectURL(url);},[source]);

  const selectedMethod=useMemo(()=>methods.find(m=>m.method===method),[methods,method]);
  const selectedCandidate=candidates[selectedIndex]??null;
  const filteredAssets=assets.filter(a=>`${a.name} ${a.asset_id} ${a.category} ${a.tags.join(' ')}`.toLowerCase().includes(assetSearch.toLowerCase()));

  const switchMethod=(next:string)=>{setMethod(next);setCandidates([]); if(next==='procedural')setParamsText(JSON.stringify({pattern:'stain',opacity:0.5},null,2)); else if(next==='diffusion_inpaint')setParamsText(JSON.stringify({model:'sdxl_inpaint',prompt:'a localized realistic industrial defect, same lighting and perspective',negative_prompt:'change background, text, extra objects',steps:25,guidance_scale:7.0,strength:0.95},null,2)); else setParamsText('{}');};

  const generate=async()=>{ if(!source)return setError('Source Image를 선택하세요.'); if(maskType==='manual'&&!targetMask)return setError('Manual mask를 선택하세요.'); setBusy(true);setError(null);setCandidates([]); try { const parameters=parseJsonObject(paramsText); let polygon: [number,number][] | undefined; if(maskType==='polygon'){ const parsed=JSON.parse(polygonText); if(!Array.isArray(parsed)||parsed.length<3) throw new Error('Polygon은 최소 3개 좌표가 필요합니다.'); polygon=parsed as [number,number][]; } const request:SyntheticGenerateRequest={method,defect_type:defectType,severity,count,seed:seed?Number(seed):null,mask:maskType==='manual'?{type:'manual'}:{type:maskType,center_x:centerX,center_y:centerY,width_ratio:widthRatio,height_ratio:heightRatio,polygon,feather_px:feather,parameters:{}},asset_id:assetId||null,parameters}; const res=await syntheticApi.generate(request,{sourceImage:source,targetMask:maskType==='manual'?targetMask:null,assetImage:assetId?null:assetImage,assetMask:assetId?null:assetMask}); if(res instanceof Blob)throw new Error('JSON response expected'); setCandidates(res.candidates);setSelectedIndex(0); } catch(e){setError(errorMessage(e));} finally{setBusy(false);} };

  const deleteAsset=async(id:string)=>{ if(!window.confirm(`${id} asset을 삭제할까요?`))return; try{await syntheticApi.deleteAsset(id);await reload();if(assetId===id)setAssetId('');}catch(e){setError(errorMessage(e));}};
  const unload=async(model?:string)=>{try{await syntheticApi.unloadDiffusion(model);await reload();}catch(e){setError(errorMessage(e));}};

  return <div className="page">
    {assetModal&&<AssetModal onClose={()=>setAssetModal(false)} onCreated={(a)=>{setAssets(v=>[a,...v]);setAssetId(a.asset_id);}}/>}
    <input ref={sourceRef} hidden type="file" accept="image/*" onChange={e=>setSource(e.target.files?.[0]??null)}/>
    <div className="page-toolbar"><div className="page-title">Synthetic NG Generator</div><span className="page-subtitle">정상 이미지에 국소 Synthetic anomaly 생성</span><Button onClick={()=>setAssetModal(true)}>Add Asset</Button><Button onClick={()=>sourceRef.current?.click()}>Open Source</Button><Button variant="primary" onClick={generate} disabled={!source||busy}>{busy?'Generating...':'Generate'}</Button></div>
    {error&&<div className="status-strip"><InlineError message={error}/></div>}
    <div className="page-content synthetic-page">
      <div className="synthetic-layout">
        <Panel title="Generator" subtitle={selectedMethod?.description} flush><div className="synthetic-form-scroll">
          <Field label="Method"><select className="select" value={method} onChange={e=>switchMethod(e.target.value)}>{methods.map(m=><option value={m.method} key={m.method}>{m.display_name}</option>)}</select></Field>
          {selectedMethod&&<div className="method-capabilities"><Badge status={selectedMethod.requires_asset?'failed':'completed'}>{selectedMethod.requires_asset?'Asset required':'Asset optional'}</Badge>{selectedMethod.optional_dependencies.map(d=><Badge key={d}>{d}</Badge>)}</div>}
          <Field label="Defect Type"><input className="input" value={defectType} onChange={e=>setDefectType(e.target.value)}/></Field>
          <Field label="Severity"><input className="input" type="number" min={0} max={1} step={0.05} value={severity} onChange={e=>setSeverity(Number(e.target.value))}/></Field>
          <Field label="Count"><input className="input" type="number" min={1} max={16} value={count} onChange={e=>setCount(Number(e.target.value))}/></Field>
          <Field label="Seed"><input className="input" type="number" placeholder="auto" value={seed} onChange={e=>setSeed(e.target.value)}/></Field>
          <div className="divider"/><div className="inspector-heading">Target Mask</div>
          <Field label="Mask Type"><select className="select" value={maskType} onChange={e=>setMaskType(e.target.value)}>{maskTypes.map(x=><option key={x}>{x}</option>)}</select></Field>
          {maskType==='manual'?<Field label="Target Mask File"><input type="file" accept="image/*" onChange={e=>setTargetMask(e.target.files?.[0]??null)}/></Field>:<><Field label="Center X"><input className="input" type="number" min={0} max={1} step={0.01} value={centerX} onChange={e=>setCenterX(Number(e.target.value))}/></Field><Field label="Center Y"><input className="input" type="number" min={0} max={1} step={0.01} value={centerY} onChange={e=>setCenterY(Number(e.target.value))}/></Field><Field label="Width Ratio"><input className="input" type="number" min={0.01} max={1} step={0.01} value={widthRatio} onChange={e=>setWidthRatio(Number(e.target.value))}/></Field><Field label="Height Ratio"><input className="input" type="number" min={0.01} max={1} step={0.01} value={heightRatio} onChange={e=>setHeightRatio(Number(e.target.value))}/></Field>{maskType==='polygon'&&<Field label="Polygon (normalized JSON)"><textarea className="json-input compact" value={polygonText} onChange={e=>setPolygonText(e.target.value)}/></Field>}<Field label="Feather px"><input className="input" type="number" min={0} max={128} value={feather} onChange={e=>setFeather(Number(e.target.value))}/></Field></>}
          {selectedMethod?.supports_asset&&<><div className="divider"/><div className="inspector-heading">Asset</div><Field label="Stored Asset"><select className="select" value={assetId} onChange={e=>{const id=e.target.value;setAssetId(id);if(id){setAssetImage(null);setAssetMask(null);}}}><option value="">None / upload below</option>{assets.map(a=><option key={a.asset_id} value={a.asset_id}>{a.name} ({a.category})</option>)}</select></Field><Field label="Asset Image"><input type="file" accept="image/*" disabled={!!assetId} onChange={e=>setAssetImage(e.target.files?.[0]??null)}/></Field><Field label="Asset Mask"><input type="file" accept="image/*" disabled={!!assetId} onChange={e=>setAssetMask(e.target.files?.[0]??null)}/></Field></>}
          <div className="divider"/><div className="inspector-heading">Method Parameters (JSON)</div>{method==='procedural'&&<div className="quick-param-row">{proceduralPatterns.map(p=><Button key={p} variant="ghost" onClick={()=>setParamsText(JSON.stringify({pattern:p,opacity:0.5},null,2))}>{p}</Button>)}</div>}<textarea className="json-input" value={paramsText} onChange={e=>setParamsText(e.target.value)}/>
        </div></Panel>
        <Panel title="Preview" subtitle={source?.name ?? 'Source image'} flush><div className="synthetic-preview-stage">{sourceUrl?<img src={sourceUrl} alt="source"/>:<EmptyState>Open Source로 정상 이미지를 선택하세요.</EmptyState>}</div></Panel>
        <Panel title="Result" subtitle={`${candidates.length} candidate(s)`} flush><Tabs items={['Generated','Mask','Difference','Metrics']} active={resultTab} onChange={setResultTab}/><div className="synthetic-result-body">{!selectedCandidate?<EmptyState>Generate 후 결과가 표시됩니다.</EmptyState>:resultTab==='Metrics'?<div className="metric-stack"><Kpi label="Changed Area" value={`${((selectedCandidate.metadata.quality?.changed_area_ratio??0)*100).toFixed(2)}%`}/><Kpi label="Inside Mean Diff" value={number(selectedCandidate.metadata.quality?.inside_mask_mean_abs_diff)}/><Kpi label="Outside Mean Diff" value={number(selectedCandidate.metadata.quality?.outside_mask_mean_abs_diff)}/><Kpi label="Outside Max Diff" value={number(selectedCandidate.metadata.quality?.outside_mask_max_abs_diff)}/></div>:<img src={imageDataUrl(selectedCandidate.images[resultTab==='Generated'?'image':resultTab==='Mask'?'mask':'difference'])} alt={resultTab}/>}</div><div className="candidate-strip">{candidates.map((c,i)=><button key={c.index} className={`candidate-btn ${selectedIndex===i?'active':''}`} onClick={()=>setSelectedIndex(i)}>#{i+1}<span>seed {c.seed}</span></button>)}</div></Panel>
        <Panel title="Asset Library" actions={<div style={{width:160}}><SearchInput placeholder="Asset 검색" value={assetSearch} onChange={e=>setAssetSearch(e.target.value)}/></div>} flush><div className="asset-list">{filteredAssets.length?filteredAssets.map(a=><div className={`asset-row ${assetId===a.asset_id?'active':''}`} key={a.asset_id} onClick={()=>setAssetId(a.asset_id)}><div><strong>{a.name}</strong><span>{a.asset_id} · {a.category} · {a.width}×{a.height}</span></div><div><Badge status={a.has_mask?'completed':''}>{a.has_mask?'mask':'no mask'}</Badge><Button variant="ghost" onClick={(e)=>{e.stopPropagation();void deleteAsset(a.asset_id);}}>×</Button></div></div>):<EmptyState>No assets</EmptyState>}</div></Panel>
        <Panel title="Diffusion Runtime" flush><div className="diffusion-list">{models.map(m=><div className="diffusion-row" key={m.model}><div><strong>{m.display_name}</strong><span>{m.model_id}</span><span>{m.device} · {m.local_files_only?'local only':'download allowed'}</span></div><div><Badge status={m.dependency_available?'completed':'failed'}>{m.dependency_available?'dependency ready':'dependency missing'}</Badge><Badge status={m.loaded?'running':''}>{m.loaded?'loaded':'unloaded'}</Badge>{m.loaded&&<Button onClick={()=>void unload(m.model)}>Unload</Button>}</div></div>)}</div></Panel>
      </div>
    </div>
  </div>;
}
